-- Borrado de tablas si existen (opcional)
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE empleado CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE departamento CASCADE CONSTRAINTS';
EXCEPTION WHEN OTHERS THEN NULL;
END;
/

-- Creación de la tabla departamento
CREATE TABLE departamento (
    id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(20) NOT NULL,
    presupuesto NUMBER(15,2) NOT NULL,
    gastos NUMBER(15,2) NOT NULL
);

-- Creación de la tabla empleado
CREATE TABLE empleado (
    id NUMBER(10) GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    nif VARCHAR2(9) NOT NULL UNIQUE,
    nombre VARCHAR2(20) NOT NULL,
    apellido1 VARCHAR2(20) NOT NULL,
    apellido2 VARCHAR2(20),
    id_departamento NUMBER(10),
    CONSTRAINT fk_empleado_depto FOREIGN KEY (id_departamento) 
        REFERENCES departamento(id)
);

-- Inserción de datos (Departamento)
INSERT INTO departamento (id, nombre, presupuesto, gastos) VALUES (1, 'Desarrollo', 120000, 6000);
INSERT INTO departamento (id, nombre, presupuesto, gastos) VALUES (2, 'Sistemas', 150000, 21000);
INSERT INTO departamento (id, nombre, presupuesto, gastos) VALUES (3, 'Recursos Humanos', 280000, 25000);
INSERT INTO departamento (id, nombre, presupuesto, gastos) VALUES (4, 'Contabilidad', 110000, 3000);
INSERT INTO departamento (id, nombre, presupuesto, gastos) VALUES (5, 'I+D', 375000, 380000);
INSERT INTO departamento (id, nombre, presupuesto, gastos) VALUES (6, 'Proyectos', 0, 0);
INSERT INTO departamento (id, nombre, presupuesto, gastos) VALUES (7, 'Publicidad', 0, 1000);

-- Inserción de datos (Empleado)
INSERT INTO empleado (id, nif, nombre, apellido1, apellido2, id_departamento) VALUES (1, '32481596F', 'Aaron', 'Rivero', 'Gomez', 1);
INSERT INTO empleado (id, nif, nombre, apellido1, apellido2, id_departamento) VALUES (2, 'Y5575632D', 'Adela', 'Salas', 'Diaz', 2);
INSERT INTO empleado (id, nif, nombre, apellido1, apellido2, id_departamento) VALUES (3, 'R6970642B', 'Adolfo', 'Rubio', 'Flores', 3);
INSERT INTO empleado (id, nif, nombre, apellido1, apellido2, id_departamento) VALUES (4, '77705545E', 'Adrian', 'Suarez', NULL, 4);
INSERT INTO empleado (id, nif, nombre, apellido1, apellido2, id_departamento) VALUES (5, '17087203C', 'Marcos', 'Loyola', 'Mendez', 5);
INSERT INTO empleado (id, nif, nombre, apellido1, apellido2, id_departamento) VALUES (6, '38382980M', 'Maria', 'Santana', 'Moreno', 1);
INSERT INTO empleado (id, nif, nombre, apellido1, apellido2, id_departamento) VALUES (7, '80576669X', 'Pilar', 'Ruiz', NULL, 2);
INSERT INTO empleado (id, nif, nombre, apellido1, apellido2, id_departamento) VALUES (8, '71651431Z', 'Pepe', 'Ruiz', 'Santana', 3);
INSERT INTO empleado (id, nif, nombre, apellido1, apellido2, id_departamento) VALUES (9, '56399183D', 'Juan', 'Gomez', 'Lopez', 2);
INSERT INTO empleado (id, nif, nombre, apellido1, apellido2, id_departamento) VALUES (10, '46384486H', 'Diego','Flores', 'Salas', 5);
INSERT INTO empleado (id, nif, nombre, apellido1, apellido2, id_departamento) VALUES (11, '67389283A', 'Marta','Herrera', 'Gil', 1);
INSERT INTO empleado (id, nif, nombre, apellido1, apellido2, id_departamento) VALUES (12, '41234836R', 'Irene','Salas', 'Flores', NULL);
INSERT INTO empleado (id, nif, nombre, apellido1, apellido2, id_departamento) VALUES (13, '82635162B', 'Juan Antonio','Saez', 'Guerrero', NULL);

COMMIT;