CREATE TABLE COCHE (
    MATRICULA VARCHAR2(10) PRIMARY KEY,
    MARCA VARCHAR2(20),
    MODELO VARCHAR2(20),
    COLOR VARCHAR2(20),
    PRECIOHORA NUMBER(10,2)
);

CREATE TABLE CLIENTE (
    CODCLIENTE VARCHAR2(10) PRIMARY KEY,
    DNI VARCHAR2(10) UNIQUE,
    NOMBRE VARCHAR2(100),
    DIRECCION VARCHAR2(100),
    TELEFONO VARCHAR2(20)
);

CREATE TABLE RESERVA (
    NUMERO VARCHAR2(10) PRIMARY KEY,
    FECHAINICIO DATE,
    FECHAFIN DATE,
    PRECIOTOTAL NUMBER (10,2),
    CODCLIENTE VARCHAR2(10),
    FOREIGN KEY (CODCLIENTE) REFERENCES CLIENTE(CODCLIENTE)
);

CREATE TABLE AVALA (
    AVALADO VARCHAR2(10),
    AVALADOR VARCHAR2(10),
    PRIMARY KEY (AVALADO),
    FOREIGN KEY (AVALADO,AVALADOR) REFERENCES CLIENTE(CODCLIENTE)
);

CREATE TABLE INCLUYE (
    NUMERO VARCHAR2(10),
    MATRICULA VARCHAR2(10),
    LITROSGAS NUMBER (10,2),
    PRIMARY KEY (NUMERO, MATRICULA),
    FOREIGN KEY (NUMERO) REFERENCES RESERVA(NUMERO),
    FOREIGN KEY (MATRICULA)REFERENCES COCHE(MATRICULA)
);
