


CREATE TABLE DEPARTAMENTO (
    ID VARCHAR2(10) PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    UBICACION VARCHAR2(100)
);

CREATE TABLE JEFE (
    ID VARCHAR2(10) PRIMARY KEY,
    DNI VARCHAR2(10) UNIQUE,
    NOMBRE VARCHAR2(100),
    SALARIO NUMBER(10),
    TELEFONO VARCHAR2(20),
    IDDEP VARCHAR2(10),
    CONSTRAINT FK_IDEDEP FOREIGN KEY (IDDEP) REFERENCES DEPARTAMENTO(ID),
    CONSTRAINT UQ_IDEDEP UNIQUE (IDDEP)
);

CREATE TABLE EMPLEADO (
    ID VARCHAR2(10) PRIMARY KEY,
    DNI VARCHAR2(10) UNIQUE,
    NOMBRE VARCHAR2(100),
    TELEFONO VARCHAR2(20),
    IDDEP VARCHAR2(10),
    
    CONSTRAINT FK_IDEDEP2 FOREIGN KEY (IDDEP) REFERENCES DEPARTAMENTO(ID)
);