


CREATE TABLE REGION (
    CODREGION VARCHAR2(10) PRIMARY KEY,
    NOMBRE VARCHAR2(100)
);

CREATE TABLE PROVINCIA (
    CODPROVINCIA VARCHAR2(10) PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    CODREGION VARCHAR2(10),
    CONSTRAINT FK_COD_REG FOREIGN KEY (CODREGION) REFERENCES REGION(CODREGION)
);

CREATE TABLE LOCALIDAD (
    CODLOCALIDAD VARCHAR2(10) PRIMARY KEY,
    NOMBRE VARCHAR2 (100),
    CODPROVINCIA VARCHAR2(10),
    CONSTRAINT FK_COD_PROV FOREIGN KEY (CODPROVINCIA) REFERENCES PROVINCIA(CODPROVINCIA)
);

CREATE TABLE EMPLEADO (
    DNI VARCHAR2(10) PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    FECHA_NAC DATE,
    TELEFONO VARCHAR2(20),
    SALARIO NUMBER(10),
    CODLOCALIDAD VARCHAR2(10),
    CONSTRAINT FK_COD_LOC FOREIGN KEY (CODLOCALIDAD) (REFERENCES) LOCALIDAD(CODLOCALIDAD)
);

