CREATE TABLE FABRICANTES (
    COD_FABRICANTE NUMBER(3) PRIMARY KEY,
    NOMBRE VARCHAR2(15) CHECK (NOMBRE = UPPER(NOMBRE)),
    PAIS VARCHAR2(15) CHECK (PAIS = UPPER(PAIS))
);

CREATE TABLE ARTICULOS (
    ARTICULO VARCHAR2(20) NOT NULL,
    COD_FABRICANTE NUMBER(3) NOT NULL,
    PESO NUMBER(3) NOT NULL CHECK (PESO > 0),
    CATEGORIA VARCHAR2(10) NOT NULL CHECK (CATEGORIA IN ('Primera','Segunda','Tercera')),
    PRECIO_VENTA NUMBER(4) CHECK (PRECIO_VENTA > 0),
    PRECIO_COSTO NUMBER(4) CHECK (PRECIO_COSTO > 0),
    EXISTENCIAS NUMBER(5),
    PRIMARY KEY (ARTICULO, COD_FABRICANTE, PESO, CATEGORIA),
    FOREIGN KEY (COD_FABRICANTE) REFERENCES FABRICANTES(COD_FABRICANTE)
);

CREATE TABLE TIENDAS (
    NIF VARCHAR2(10) PRIMARY KEY,
    NOMBRE VARCHAR2(20),
    DIRECCION VARCHAR2(20),
    POBLACION VARCHAR2(20),
    PROVINCIA VARCHAR2(20) CHECK (PROVINCIA = UPPER(PROVINCIA)),
    CODPOSTAL NUMBER(5)
);

CREATE TABLE PEDIDOS (
    NIF VARCHAR2(10) NOT NULL,
    ARTICULO VARCHAR2(20) NOT NULL,
    COD_FABRICANTE NUMBER(3) NOT NULL,
    PESO NUMBER(3) NOT NULL,
    CATEGORIA VARCHAR2(10) NOT NULL CHECK (CATEGORIA IN ('Primera','Segunda','Tercera')),
    FECHA_PEDIDO DATE NOT NULL,
    UNIDADES_PEDIDAS NUMBER(4) CHECK (UNIDADES_PEDIDAS > 0),

    CONSTRAINT pk1 PRIMARY KEY (NIF, ARTICULO, COD_FABRICANTE, PESO, CATEGORIA, FECHA_PEDIDO),
    CONSTRAINT fk3 FOREIGN KEY (NIF) REFERENCES TIENDAS(NIF),
    CONSTRAINT fk4 FOREIGN KEY (ARTICULO, COD_FABRICANTE, PESO, CATEGORIA) REFERENCES ARTICULOS(ARTICULO, COD_FABRICANTE, PESO, CATEGORIA)
);


CREATE TABLE VENTAS (
    NIF VARCHAR2(10) NOT NULL,
    ARTICULO VARCHAR2(20) NOT NULL,
    COD_FABRICANTE NUMBER(3) NOT NULL,
    PESO NUMBER(3) NOT NULL,
    CATEGORIA VARCHAR2(10) NOT NULL,
    FECHA_VENTA DATE NOT NULL,
    UNIDADES_VENDIDAS NUMBER(4)
);


ALTER TABLE VENTAS ADD CONSTRAINT PK_VENTAS PRIMARY KEY (NIF, ARTICULO, COD_FABRICANTE, PESO, CATEGORIA, FECHA_VENTA);

ALTER TABLE VENTAS ADD CONSTRAINT FK_VENTAS_FAB FOREIGN KEY (COD_FABRICANTE) REFERENCES FABRICANTES(COD_FABRICANTE);

ALTER TABLE VENTAS ADD CONSTRAINT FK_VENTAS_TIENDA FOREIGN KEY (NIF) REFERENCES TIENDAS(NIF);

ALTER TABLE VENTAS ADD CONSTRAINT FK_VENTAS_ART FOREIGN KEY (ARTICULO, COD_FABRICANTE, PESO, CATEGORIA) REFERENCES ARTICULOS(ARTICULO, COD_FABRICANTE, PESO, CATEGORIA);

ALTER TABLE VENTAS ADD CONSTRAINT CK_VENTAS_UNIDADES CHECK (UNIDADES_VENDIDAS > 0);

ALTER TABLE VENTAS ADD CONSTRAINT CK_VENTAS_CATEGORIA CHECK (CATEGORIA IN ('Primera','Segunda','Tercera'));
