CREATE TABLE SUCURSAL (
    CODSUCURSAL NUMBER(10),
    NOMBRE VARCHAR2(100),
    DIRECCION VARCHAR2(100),
    LOCALIDAD VARCHAR2(100)
);

CREATE TABLE CLIENTE (
    DNI VARCHAR2(10),
    NOMBRE VARCHAR2(100),
    DIRECCION VARCHAR2(100),
    LOCALIDAD VARCHAR2(100),
    FECHA_NAC DATE,
    SEXO VARCHAR2(10)
);

CREATE TABLE CUENTA (
    CODSUCURSAL NUMBER(10),
    CODCUENTA NUMBER (10)
);

CREATE TABLE CLICUENTA(
    CODSUCURSAL NUMBER(10),
    CODCUENTA NUMBER (10),
    DNI VARCHAR2(10)
);

CREATE TABLE TRANSACCION (
    CODSUCURSAL NUMBER(10),
    CODCUENTA NUMBER (10),
    NUMTRANSACCION NUMBER(10),
    FECHA DATE,
    CANTIDAD NUMBER(10),
    TIPO VARCHAR2(10)
);


ALTER TABLE SUCURSAL ADD CONSTRAINT PK_SUCURSAL PRIMARY KEY (CODSUCURSAL);


ALTER TABLE CLIENTE ADD CONSTRAINT PK_CLIENTE PRIMARY KEY (DNI);


ALTER TABLE CUENTA ADD CONSTRAINT PK_CUENTA PRIMARY KEY (CODCUENTA);

ALTER TABLE CUENTA ADD CONSTRAINT FK_CUENTA_SUCURSAL FOREIGN KEY (CODSUCURSAL) REFERENCES SUCURSAL(CODSUCURSAL);

ALTER TABLE CLICUENTA ADD CONSTRAINT PK_CLICUENTA PRIMARY KEY (CODSUCURSAL, CODCUENTA, DNI);

ALTER TABLE CLICUENTA ADD CONSTRAINT FK_CLICUENTA_SUCURSAL FOREIGN KEY (CODSUCURSAL) REFERENCES SUCURSAL(CODSUCURSAL);

ALTER TABLE CLICUENTA ADD CONSTRAINT FK_CLICUENTA_CUENTA FOREIGN KEY (CODCUENTA) REFERENCES CUENTA(CODCUENTA);

ALTER TABLE CLICUENTA ADD CONSTRAINT FK_CLICUENTA_CLIENTE FOREIGN KEY (DNI) REFERENCES CLIENTE(DNI);

ALTER TABLE TRANSACCION ADD CONSTRAINT PK_TRANSACCION PRIMARY KEY (CODSUCURSAL, CODCUENTA, NUMTRANSACCION);

ALTER TABLE TRANSACCION ADD CONSTRAINT FK_TRANSACCION_SUCURSAL FOREIGN KEY (CODSUCURSAL) REFERENCES SUCURSAL(CODSUCURSAL);

ALTER TABLE TRANSACCION ADD CONSTRAINT FK_TRANSACCION_CUENTA FOREIGN KEY (CODCUENTA) REFERENCES CUENTA(CODCUENTA);






