CREATE TABLE SUCURSAL (
    CODSUCURSAL NUMBER(10) PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    DIRECCION VARCHAR2(100),
    LOCALIDAD VARCHAR2(100)
);

CREATE TABLE CLIENTE (
    DNI VARCHAR2(10) PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    DIRECCION VARCHAR2(100),
    LOCALIDAD VARCHAR2(100),
    FECHA_NAC DATE,
    SEXO VARCHAR2(10)
);

CREATE TABLE CUENTA (
    CODSUCURSAL NUMBER(10),
    CODCUENTA NUMBER (10) PRIMARY KEY,
    CONSTRAINT PK_RECIBE PRIMARY KEY (CODSUCURSAL),
    CONSTRAINT FK_CDS FOREIGN KEY (CODSUCURSAL) REFERENCES SUCURSAL(CODSUCURSAL)
    
);

CREATE TABLE CLICUENTA(
    CODSUCURSAL NUMBER(10),
    CODCUENTA NUMBER (10),
    DNI VARCHAR2(10),
    CONSTRAINT PK PRIMARY KEY (CODSUCURSAL, CODCUENTA, DNI),
    CONSTRAINT FK_CDS3 FOREIGN KEY (CODSUCURSAL) REFERENCES SUCURSAL(CODSUCURSAL),
    CONSTRAINT FK_CDS4 FOREIGN KEY (CODCUENTA) REFERENCES CUENTA(CODCUENTA),
    CONSTRAINT FK_CDS5 FOREIGN KEY (DNI) REFERENCES CLIENTE(DNI)

);



CREATE TABLE TRANSACCION (
    CODSUCURSAL NUMBER(10),
    CODCUENTA NUMBER (10),
    NUMTRANSACCION NUMBER(10),
    FECHA DATE,
    CANTIDAD NUMBER(10),
    TIPO VARCHAR2(10),
    CONSTRAINT PK2 PRIMARY KEY (CODSUCURSAL, CODCUENTA, NUMTRANSACCION),
    CONSTRAINT FK_CDS5 FOREIGN KEY (CODSUCURSAL) REFERENCES SUCURSAL(CODSUCURSAL),
    CONSTRAINT FK_CDS6 FOREIGN KEY (CODCUENTA) REFERENCES CLICUENTA(CODCUENTA)
);