
CREATE TABLE ALUMNO (
    NUMMATRICULA NUMBER(10) PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    FECHA_NACIMIENTO DATE,
    TELEFONO VARCHAR2(20)
);

CREATE TABLE PROFESOR (
    IDPROFESOR NUMBER(10) PRIMARY KEY,
    NIF_P VARCHAR2(20) UNIQUE,
    NOMBRE VARCHAR2(100),
    ESPECIALIDAD VARCHAR2(100),
    TELEFONO VARCHAR2(20)
);

CREATE TABLE ASIGNATURA (
    CODASIGNATURA VARCHAR2(10) PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    IDPROFESOR NUMBER(10) NOT NULL,
    CONSTRAINT FK FOREIGN KEY (IDPROFESOR)
        REFERENCES PROFESOR(IDPROFESOR)
);

CREATE TABLE RECIBE (
    NUMMATRICULA NUMBER(10),
    CODASIGNATURA VARCHAR2(10),
    CURSOESCOLAR VARCHAR2(50),
    CONSTRAINT PK_RECIBE PRIMARY KEY (NUMMATRICULA, CODASIGNATURA),
    CONSTRAINT FK_RECIBE_ALUMNO FOREIGN KEY (NUMMATRICULA)
        REFERENCES ALUMNO(NUMMATRICULA),
    CONSTRAINT FK_RECIBE_ASIG FOREIGN KEY (CODASIGNATURA)
        REFERENCES ASIGNATURA(CODASIGNATURA)
);
