CREATE TABLE SUCURSAL (
    CODSUCURSAL NUMBER(10),
    NOMBRE VARCHAR2(100),
    DIRECCION VARCHAR2(100),
    LOCALIDAD VARCHAR2(100)
);

CREATE TABLE CLIENTE (
    DNI VARCHAR2(10),
    NOMBRE VARCHAR2(100),
    DIRECCION VARCHAR2(100),
    LOCALIDAD VARCHAR2(100),
    FECHA_NAC DATE,
    SEXO VARCHAR2(10)
);

CREATE TABLE CUENTA (
    CODSUCURSAL NUMBER(10),
    CODCUENTA NUMBER (10)
    
    
);

CREATE TABLE CLICUENTA(
    CODSUCURSAL NUMBER(10),
    CODCUENTA NUMBER (10),
    DNI VARCHAR2(10)
    

);

CREATE TABLE TRANSACCION (
    CODSUCURSAL NUMBER(10),
    CODCUENTA NUMBER (10),
    NUMTRANSACCION NUMBER(10),
    FECHA DATE,
    CANTIDAD NUMBER(10),
    TIPO VARCHAR2(10)
    
);

    ALTER TABLE SUCURSAL CONSTRAINT PK_RECIBE PRIMARY KEY (CODSUCURSAL),


    ALTER TABLE CUENTA CONSTRAINT FK_CDS FOREIGN KEY (CODSUCURSAL) REFERENCES SUCURSAL(CODSUCURSAL)



    ALTER TABLE CLICUENTA CONSTRAINT PK PRIMARY KEY (CODSUCURSAL, CODCUENTA, DNI),
    ALTER TABLE CLICUENTA CONSTRAINT FK_CDS3 FOREIGN KEY (CODSUCURSAL) REFERENCES SUCURSAL(CODSUCURSAL),
    ALTER TABLE CLICUENTA CONSTRAINT FK_CDS4 FOREIGN KEY (CODCUENTA) REFERENCES CUENTA(CODCUENTA),
    ALTER TABLE CLICUENTA CONSTRAINT FK_CDS5 FOREIGN KEY (DNI) REFERENCES CLIENTE(DNI)

    ALTER TABLE CLIENTE CONSTRAINT PK_DNI PRIMARY KEY (DNI),

    ALTER TABLE TRANSACCION CONSTRAINT PK2 PRIMARY KEY (CODSUCURSAL, CODCUENTA, NUMTRANSACCION),
    ALTER TABLE TRANSACCION CONSTRAINT FK_CDS5 FOREIGN KEY (CODSUCURSAL) REFERENCES SUCURSAL(CODSUCURSAL),
    ALTER TABLE TRANSACCION CONSTRAINT FK_CDS6 FOREIGN KEY (CODCUENTA) REFERENCES CLICUENTA(CODCUENTA)