CREATE TABLE DIRECTOR (
    NOMBRE VARCHAR2(100) PRIMARY KEY,
    NACIONALIDAD VARCHAR2(100)
);

CREATE TABLE PELICULA (
    ID VARCHAR2(20) PRIMARY KEY,
    TITULO VARCHAR2(100),
    PRODUCTORA VARCHAR2(100),
    NACIONALIDAD VARCHAR2(20),
    FECHA DATE,
    DIRECTOR VARCHAR2(100),
    FOREIGN KEY (DIRECTOR) REFERENCES DIRECTOR(NOMBRE)
);

CREATE TABLE EJEMPLAR (
    IDPELI VARCHAR2(20),
    NUMERO VARCHAR2 (20),
    ESTADO VARCHAR2(50),
    PRIMARY KEY (IDPELI,NUMERO),
    FOREIGN KEY (IDPELI) REFERENCES PELICULA(ID)
);

CREATE TABLE ACTORES(
    NOMBRE VARCHAR2(100) PRIMARY KEY,
    NACIONALIDAD VARCHAR2(20),
    SEXO VARCHAR2(1) CHECK (SEXO IN ('M','H'))
);

CREATE TABLE ACTUA (
    ACTOR VARCHAR2(100),
    IDPELI VARCHAR2(20),
    PROTA VARCHAR2(2) DEFAULT 'NO' CHECK (PROTA IN ('SI','NO')),
    PRIMARY KEY (ACTOR,IDPELI),
    FOREIGN KEY (ACTOR) REFERENCES ACTORES(NOMBRE),
    FOREIGN KEY (IDPELI) REFERENCES PELICULA(ID)
);

CREATE TABLE SOCIO (
    DNI VARCHAR2(10) PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    DIRECCION VARCHAR2(100),
    TELEFONO VARCHAR2(20),
    AVALADOR VARCHAR2(10),
    FOREIGN KEY (AVALADOR) REFERENCES SOCIO(DNI)
);

CREATE TABLE ALQUILA(
    DNI VARCHAR2(20),
    IDPELI VARCHAR2(20),
    NUMERO VARCHAR2(20),
    FECHAALQUILER DATE,
    FECHADEVOLUCION DATE ,
    CONSTRAINT CHK CHECK (FECHADEVOLUCION>FECHAALQUILER),
    PRIMARY KEY (DNI,IDPELI,NUMERO, FECHAALQUILER),
    FOREIGN KEY (DNI) REFERENCES SOCIO(DNI),
    FOREIGN KEY (IDPELI) REFERENCES PELICULA(ID),
    FOREIGN KEY (IDPELI,NUMERO) REFERENCES EJEMPLAR(IDPELI,NUMERO)
);