CREATE TABLE PERIODISTA (
    DNI VARCHAR2(20) PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    DIRECCION VARCHAR2(100),
    TELEFONO VARCHAR2(20),
    ESPECIALISTA VARCHAR2(100)
);

CREATE TABLE SUCURSAL (
    CODIGO VARCHAR2(20) PRIMARY KEY,
    DIRECCION VARCHAR2(100),
    TELEFONO VARCHAR2(20)
);

CREATE TABLE REVISTA(
    NUMREG VARCHAR2(20) PRIMARY KEY,
    TITULO VARCHAR2(100),
    PERIOCIDAD VARCHAR2(20),
    TIPO VARCHAR2(20),
    SUCURSAL VARCHAR2(20),
    FOREIGN KEY (SUCURSAL) REFERENCES SUCURSAL(CODIGO)
);


CREATE TABLE NUMREVISTA (
    NUMREG VARCHAR2(20),
    NUMERO VARCHAR2 (20),
    NUMPAGINAS NUMBER(10),
    FECHA DATE,
    CANTVENDIDAS NUMBER(10),
    PRIMARY KEY (NUMREG,NUMERO),
    FOREIGN KEY (NUMREG) REFERENCES REVISTA(NUMREG)
);

CREATE TABLE EMPLEADO (
    DNI VARCHAR2(10) PRIMARY KEY,
    NOMBRE VARCHAR2(100),
    DIRECCION VARCHAR2(100),
    TELEFONO VARCHAR2(20),
    SUCURSAL VARCHAR2(20),
    FOREIGN KEY (SUCURSAL) REFERENCES SUCURSAL(CODIGO)
);

CREATE TABLE ESCRIBE (
    NUMREG VARCHAR2(20),
    DNI VARCHAR2(10),
    PRIMARY KEY (NUMREG,DNI),
    FOREIGN KEY (NUMREG) REFERENCES REVISTA(NUMREG),
    FOREIGN KEY (DNI) REFERENCES PERIODISTA(DNI)
);