

CREATE TABLE Tienda(
    NIF VARCHAR2(10),
    NOMBRE VARCHAR2(20) NOT NULL,
    DIRECCION VARCHAR2(20),
    POBLACION VARCHAR2(20),
    PROVINCIA VARCHAR2(20) CHECK (PROVINCIA = UPPER(PROVINCIA)),
    CODPOSTAL NUMBER(5)
    CONSTRAINT PK_TIENDAS PRIMARY KEY (NIF)
);

CREATE TABLE Fabricante (
    COD_FABRICANTE NUMBER(3),
    NOMBRE VARCHAR2(15) CHECK (NOMBRE = UPPER(NOMBRE)),
    PAIS VARCHAR2(15)  CHECK (PAIS = UPPER(PAIS)),
    CONSTRAINT PK_FABRICANTE PRIMARY KEY (COD_FABRICANTE)
);

CREATE TABLE Articulos (
    ARTICULO VARCHAR2(20),
    COD_FABRICANTE NUMBER(3),
    PESO NUMBER(3),
    CATEGORIA VARCHAR2(10),
    PRECIO_VENTA NUMBER(6),
    PRECIO_COSTO NUMBER(6),
    EXISTENCIAS NUMBER(5),
    CONSTRAINT pk_articulos PRIMARY KEY (ARTICULO, COD_FABRICANTE, PESO, CATEGORIA)

);


CREATE TABLE Ventas (
    NIF VARCHAR2(10),
    ARTICULO VARCHAR2(20),
    COD_FABRICANTE NUMBER(3),
    PESO NUMBER(3),
    CATEGORIA VARCHAR2(10) CHECK(CATEGORIA IN ('PRIMERA','SEGUNDA','TERCERA')),
    FECHA_VENTA DATE,
    UNIDADES_VENDIDAS NUMBER(4) CHECK (UNIDADES_VENDIDAS=(UNIDADES_VENDIDAS>0))

    CONSTRAINTS FORANEAS {

    }
)
